---
title: "Linear Model"
author: "Ruixi Li"
date: "2023-11-09"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

# data importing

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

```{r}
nyc_airbnb |>
  ggplot(aes(x=stars, y=price, color= borough))+
  geom_point()
```


# Model fitting

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

let's look at the results

```{r}
fit
# formatted matrix
summary(fit)
summary(fit)$coef
coef(fit)
residuals(fit)
# formatted df
broom::glance(fit)
broom::tidy(fit)|>
  select(-std.error, -statistic) |>
  mutate(
    term = str_replace(term,"borough","Borough:")) |>
  knitr::kable(digits = 3)
```

# be in control of factors

factors is considered there's a alphabetical order, so by default, Bronx is the reference group
in order to change refernce grouop to the most common borough, you can ...

```{r}
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + borough, data = nyc_airbnb)

broom::tidy(fit)
```

# Diagnostics

```{r}
modelr::add_residuals(nyc_airbnb,fit) |>
  ggplot(aes(x=borough, y=resid))+
  geom_violin()+
  ylim(-500,1500)



modelr::add_residuals(nyc_airbnb,fit) |>
  ggplot(aes(x=stars, y=resid))+
  geom_point()+
  facet_grid(.~ borough)

```

# Hypothesis test

this do ttest by default

```{r}
fit |>
  broom::tidy()
```

what about the significance of `borough`

```{r}
fit_null=lm(price~stars, data=nyc_airbnb)
fit_alt=lm(price~stars+borough, data=nyc_airbnb)

anova(fit_null, fit_alt)|>
  broom::tidy()
```

